# Generated by Django 5.0.6 on 2024-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('region_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('street_number', models.IntegerField()),
                ('apartment_number', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
