# Generated by Django 5.0.6 on 2024-07-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='birthdate',
        ),
    ]
